services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
  backend:
    image: node:23-alpine
    container_name: backend
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '3333:3333'
    depends_on:
      - mysql
    command: ["/bin/sh", "-c", "npm run dev"]
    environment:
      - HOST=0.0.0.0
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=example
      - DB_PASSWORD=example
      - DB_DATABASE=example

volumes:
  mysql_data:
