services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend
    environment:
      - NODE_ENV=production
      - PORT=3333
      - APP_KEY=ZS2g54yredyy7kC2kic6L7t4s1Y-NrOU
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - SESSION_DRIVER=cookie
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=example
      - DB_PASSWORD=example
      - DB_DATABASE=example
    networks:
      - dokploy-network

volumes:
  mysql_data:

networks:
  dokploy-network:
    external: true
