services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dokploy-network
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - dokploy-network
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend
    ports:
      - '3333:3333'
    depends_on:
      - mysql
    environment:
      - NODE_ENV=production
      - PORT=3333
      - APP_KEY=ZS2g54yredyy7kC2kic6L7t4s1Y-NrOU
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - SESSION_DRIVER=cookie
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=example
      - DB_PASSWORD=example
      - DB_DATABASE=example
    networks:
      - dokploy-network

volumes:
  mysql_data:

networks:
  dokploy-network:
    external: true
